name: Plant Based
favicon: null
layout_spectrum: 0.396470207022503
typography_spectrum: 0.5497121235821396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.16177588771097362
  lightness: 0.9307158631272614
  saturation: 0.7428994930814952
  rhythmicContrast: 0.552007048856467
purpose: []
